import type { Metadata } from "next";
import type { ReactElement, ReactNode } from "react";

import "@fontsource-variable/inter/index.css";
import "./globals.css";

import { AnimationProvider } from "@/components/providers/animation-provider";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }): ReactElement {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn("min-h-screen bg-background font-sans antialiased")}>
        <AnimationProvider>{children}</AnimationProvider>
      </body>
    </html>
  );
}
